services:
  reverse-proxy:
    image: traefik:v3.4
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedByDefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.letsencrypt.acme.email=admin@tum.de"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./letsencrypt:/letsencrypt

  nginx-gateway:
    image: ghcr.io/aet-devops25/team-releaserangers/nginx-gateway:latest
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx-gateway.rule=Host(`${NGINX_HOST}`)"
      - "traefik.http.services.nginx-gateway.loadbalancer.server.port=80"
      - "traefik.http.routers.nginx-gateway.entrypoints=websecure"
      - "traefik.http.routers.nginx-gateway.tls.certresolver=letsencrypt"
    depends_on:
      - authentication-service
      - coursemgmt-service
      - upload-service

  authentication-service:
    image: ghcr.io/aet-devops25/team-releaserangers/authentication-service:latest
    restart: unless-stopped
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.authentication-service.rule=Host(`${AUTH_HOST}`)"
      - "traefik.http.services.authentication-service.loadbalancer.server.port=8080"
      - "traefik.http.routers.authentication-service.entrypoints=websecure"
      - "traefik.http.routers.authentication-service.tls.certresolver=letsencrypt"

  coursemgmt-service:
    image: ghcr.io/aet-devops25/team-releaserangers/coursemgmt-service:latest
    restart: unless-stopped
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.coursemgmt-service.rule=Host(`${COURSE_HOST}`)"
      - "traefik.http.services.coursemgmt-service.loadbalancer.server.port=8080"
      - "traefik.http.routers.coursemgmt-service.entrypoints=websecure"
      - "traefik.http.routers.coursemgmt-service.tls.certresolver=letsencrypt"

  upload-service:
    image: ghcr.io/aet-devops25/team-releaserangers/upload-service:latest
    restart: unless-stopped
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.upload-service.rule=Host(`${UPLOAD_HOST}`)"
      - "traefik.http.services.upload-service.loadbalancer.server.port=8080"
      - "traefik.http.routers.upload-service.entrypoints=websecure"
      - "traefik.http.routers.upload-service.tls.certresolver=letsencrypt"
