services:
  nginx-gateway:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
    depends_on:
      - authentication-service
      - coursemgmt-service
      - upload-service
      - client
      - genai-service

  postgres-db:
    build:
      context: .
      dockerfile: Dockerfile.db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U release -d devops25_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  authentication-service:
    build:
      context: ./server/authentication-service
    ports:
      - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    env_file: .env
    depends_on:
      postgres-db:
        condition: service_healthy

  coursemgmt-service:
    build:
      context: ./server/coursemgmt-service
    ports:
      - "8082:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    env_file: .env
    depends_on:
      postgres-db:
        condition: service_healthy

  upload-service:
    build:
      context: ./server/upload-service
    ports:
      - "8083:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    env_file: .env
    depends_on:
      postgres-db:
        condition: service_healthy

  genai-service:
    build:
      context: ./genai
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: ./genai/.env
    environment:
      - COURSEMGMT_URL=http://coursemgmt-service:8080
    ports:
      - "8084:8000"
    depends_on:
      - coursemgmt-service
      - upload-service

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - authentication-service
      - coursemgmt-service
      - upload-service

volumes:
  postgres-data:
