services:
  nginx-gateway:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
    depends_on:
      - authentication-service
      - coursemgmt-service
      - upload-service

  authentication-service:
    build:
      context: ./server/authentication-service
    ports:
      - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  coursemgmt-service:
    build:
      context: ./server/coursemgmt-service
    ports:
      - "8082:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  upload-service:
    build:
      context: ./server/upload-service
    ports:
      - "8083:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker

