apiVersion: 1
groups:
  - orgId: 1
    name: UploadError
    folder: notifiers
    interval: 1m
    rules:
      - uid: ferxqmykc36kgc
        title: Upload Error Gauge Panel
        condition: C
        data:
          - refId: A
            relativeTimeRange:
              from: 21600
              to: 0
            datasourceUid: PBFA97CFB590B2093
            model:
              adhocFilters: [ ]
              datasource:
                type: prometheus
                uid: PBFA97CFB590B2093
              disableTextWrap: false
              editorMode: builder
              expr: upload_service_errors_gauge
              fullMetaSearch: false
              includeNullMetadata: true
              instant: true
              interval: ""
              intervalMs: 15000
              legendFormat: __auto
              maxDataPoints: 43200
              range: false
              refId: A
              useBackend: false
          - refId: C
            datasourceUid: __expr__
            model:
              conditions:
                - evaluator:
                    params:
                      - 0
                    type: gt
                  operator:
                    type: and
                  query:
                    params:
                      - C
                  reducer:
                    params: [ ]
                    type: last
                  type: query
              datasource:
                type: __expr__
                uid: __expr__
              expression: A
              intervalMs: 1000
              maxDataPoints: 43200
              refId: C
              type: threshold
        dashboardUid: fd7f0367-d1b0-49c1-9bdc-58ccc3aded23
        panelId: 1
        noDataState: NoData
        execErrState: Error
        for: 1m
        annotations:
          __dashboardUid__: fd7f0367-d1b0-49c1-9bdc-58ccc3aded23
          __panelId__: "1"
        labels: { }
        isPaused: false
        notification_settings:
          receiver: grafana-default-email
