apiVersion: 1

datasources:
  - name: Jaeger
    type: jaeger
    access: proxy
    url: http://jaeger:16686
    isDefault: false
    jsonData:
      tracesToLogsEnabled: true
      tracesToMetricsEnabled: true
    version: 1

