apiVersion: v1
kind: Secret
metadata:
  name: authentication-env
  namespace: releaserangers
type: Opaque
stringData:
  JWT_SECRET: 0b368593d056c6812c6a2c7cf1d561e3
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: releaserangers
type: Opaque
stringData:
  POSTGRES_USER: release
  POSTGRES_PASSWORD: ranger
  POSTGRES_DB: devops25_db
---
apiVersion: v1
kind: Secret
metadata:
  name: genai-env
  namespace: releaserangers
type: Opaque
stringData:
  LLM_API_KEY: AIzaSyBxIAvv1zoN9gozraWX4KJE_dIM8kwUXdQ
---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-credentials
  namespace: ranger-observatory
type: Opaque
stringData:
  admin-user: admin
  admin-password: admin