# This file contains the default values for the App Helm chart.

team: team-releaserangers

namespace:
  create: false

authenticationService:
  image:
    repository: ghcr.io/aet-devops25/team-releaserangers/authentication-service
    tag: latest
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 8080
    targetPort: 8080
  replicaCount: 1
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: docker

coursemgmtService:
  image:
    repository: ghcr.io/aet-devops25/team-releaserangers/coursemgmt-service
    tag: latest
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 8080
    targetPort: 8080
  replicaCount: 1
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: docker
    - name: SPRING_DATASOURCE_URL
      value: jdbc:postgresql://postgres:5432/devops25_db
    - name: SPRING_DATASOURCE_USERNAME
      value: release
    - name: SPRING_DATASOURCE_PASSWORD
      value: ranger


uploadService:
  image:
    repository: ghcr.io/aet-devops25/team-releaserangers/upload-service
    tag: latest
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 5432
    targetPort: 8080
  replicaCount: 1
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: docker

postgres:
  replicaCount: 1
  image:
    repository: postgres
    tag: 15-alpine
    pullPolicy: IfNotPresent
  auth:
    username: release
    password: ranger
    database: devops25_db
  service:
    type: ClusterIP
    port: 5432

ingress:
  enabled: true
  className: "nginx"
  tls: true
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
