{
 "title": "Authentication Service Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Total Number of Requests",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "auth_service_requests_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Current Latency of Authentication Service (ms)",
   "type": "timeseries",
   "description": "Always displays the latency of the last request to the authentication service",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "auth_service_current_latency{service=\"auth-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Amount of Requests to the Authentication Service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "auth_service_requests_total{service=\"auth-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Amount of Authentiaction Service Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "auth_service_errors_total{service=\"auth-service\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}