{
 "title": "Course Management Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Total Amount of Requests to Course Management Service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "coursemgmt_service_requests_total{service=\"coursemgmt-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency of Last Request to Course Management Service (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "coursemgmt_service_current_latency{service=\"coursemgmt-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Amount of Errors in Course Management Serevice",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "coursemgmt_service_errors_total{service=\"coursemgmt-service\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}