{
 "title": "Logs Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "CourseMgmt Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"releaserangers-app\"} |= `coursemgmt-service`"
    }
   ]
  },
  {
   "title": "AuthenticationService Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"releaserangers-app\"} |= `authentication-service`"
    }
   ]
  },
  {
   "title": "Client Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"releaserangers-app\"} |= `client`"
    }
   ]
  },
  {
   "title": "Upload Service Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"releaserangers-app\"} |= `upload-service`"
    }
   ]
  },
  {
   "title": "All Error Logs",
   "type": "logs",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"releaserangers-app\"} |= `error`"
    }
   ]
  }
 ]
}