{
 "title": "main-dashboard",
 "description": "This is our dashboard to show basic metrics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Max Upload Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "upload_service_request_duration_seconds_max",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sum of uploads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "upload_service_requests_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Sum of errors when uploading",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "upload_service_errors_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "New panel",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 19, "x": 0, "y": 16 },
   "targets": [
    { "expr": "process_virtual_memory_bytes", "legendFormat": "__auto" },
    { "expr": "application_ready_time_seconds", "legendFormat": "__auto" },
    {
     "expr": "http_server_requests_active_seconds_max",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}