{
 "title": "Summary Service Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Total Time spent Summarizing (s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "summary_service_request_duration_seconds_sum{service=\"upload-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Duration of Last Summary Service Request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "upload_service_last_summary_duration{service=\"upload-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Amount of Requests to Summary Service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "upload_service_summary_requests_total{service=\"upload-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Maximum Time needed for Summary (s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "summary_service_request_duration_seconds_max{service=\"upload-service\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}