{
 "title": "Upload Service Dashboard",
 "description": "This is our dashboard to show basic metrics",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Total Amount of Requests to Upload Service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "upload_service_requests_total{service=\"upload-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency of the last Request to Upload Service (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "upload_service_current_latency{service=\"upload-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Amount of Errors in Upload Service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "upload_service_errors_total{service=\"upload-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "New panel",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 16 },
   "targets": [
    { "expr": "process_virtual_memory_bytes", "legendFormat": "__auto" },
    { "expr": "application_ready_time_seconds", "legendFormat": "__auto" },
    {
     "expr": "http_server_requests_active_seconds_max",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}