apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication-service
  namespace: "{{ .Values.team }}"
spec:
  replicas: {{ .Values.authenticationService.replicaCount }}
  selector:
    matchLabels:
      app: authentication-service-selector
  template:
    metadata:
      labels:
        app: authentication-service-selector
    spec:
      containers:
        - name: authentication-service
          image: "{{ .Values.authenticationService.image.repository }}:{{ .Values.authenticationService.image.tag }}"
          imagePullPolicy: {{ .Values.authenticationService.image.pullPolicy }}
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "100m"
              memory: "128Mi"
          ports:
            - containerPort: {{ .Values.authenticationService.service.targetPort }}
          env:
            {{- range .Values.authenticationService.env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
