apiVersion: v1
kind: Service
metadata:
  name: authentication-service
  namespace: "{{ .Values.team }}"
spec:
  selector:
    app: authentication-service-selector
  ports:
    - port: {{ .Values.authenticationService.service.port }}
      targetPort: {{ .Values.authenticationService.service.targetPort }}
      protocol: TCP
  type: {{ .Values.authenticationService.service.type }}
