apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
  namespace: "{{ .Values.team }}"
  labels: 
    monitoring: "true"
spec:
  replicas: {{ .Values.client.replicaCount }}
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client
          image: "{{ .Values.client.image.repository }}:{{ .Values.client.image.tag }}"
          imagePullPolicy: {{ .Values.client.image.pullPolicy }}
          ports:
            - containerPort: 3000
          env:
            {{- if .Values.client.env }}
            {{- toYaml .Values.client.env | nindent 12 }}
            {{- end }}