apiVersion: v1
kind: Service
metadata:
  name: coursemgmt-service
  namespace: "{{ .Values.team }}"
spec:
  selector:
    app: coursemgmt-service-selector
  ports:
    - port: {{ .Values.coursemgmtService.service.port }}
      targetPort: {{ .Values.coursemgmtService.service.targetPort }}
      protocol: TCP
  type: {{ .Values.coursemgmtService.service.type }}
