apiVersion: v1
kind: Service
metadata:
  name: coursemgmt-service
  namespace: "{{ .Values.team }}"
spec:
  type: {{ .Values.coursemgmtService.service.type }}
  selector:
    app: coursemgmt-service
  ports:
    - port: {{ .Values.coursemgmtService.service.port }}
      targetPort: {{ .Values.coursemgmtService.service.targetPort | default 8080 }}