apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: {{ .Values.monitoring.namespace }}
data:
  datasources.yml: |-
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus.{{ .Values.monitoring.namespace }}.svc.cluster.local:{{ .Values.monitoring.prometheus.service.port }}
        isDefault: true