{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ .Release.Name }}-ingress"
  namespace: "{{ .Values.team }}"
  {{- $annotations := .Values.ingress.annotations | default dict }}
  {{- if $annotations }}
  annotations:
    {{- toYaml $annotations | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    - hosts:
        - "{{ .Values.team }}.student.k8s.aet.cit.tum.de"
      secretName: "team-releaserangers-tls"
  {{- end }}
  rules:
    - host: "{{ .Values.team }}.student.k8s.aet.cit.tum.de"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: client
                port:
                  number: {{ .Values.ingress.services.client.port }}
          - path: /auth
            pathType: Prefix
            backend:
              service:
                name: authentication-service
                port:
                  number: {{ .Values.ingress.services.authenticationService.port }}
          - path: /courses
            pathType: Prefix
            backend:
              service:
                name: coursemgmt-service
                port:
                  number: {{ .Values.ingress.services.coursemgmtService.port }}
          - path: /chapters
            pathType: Prefix
            backend:
              service:
                name: coursemgmt-service
                port:
                  number: {{ .Values.ingress.services.coursemgmtService.port }}
          - path: /favorites
            pathType: Prefix
            backend:
              service:
                name: coursemgmt-service
                port:
                  number: {{ .Values.ingress.services.coursemgmtService.port }}
          - path: /upload
            pathType: Prefix
            backend:
              service:
                name: upload-service
                port:
                  number: {{ .Values.ingress.services.uploadService.port }}
          - path: /summarize
            pathType: Prefix
            backend:
              service:
                name: genai-service
                port:
                  number: {{ .Values.ingress.services.genaiService.port }}
{{- end }}
