{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: releaserangers-ingress
  namespace: "{{ .Values.team }}"
  annotations:
    {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  tls:
    - hosts:
        - releaserangers.local
      secretName: releaserangers-tls
  rules:
    - host: releaserangers.local
      http:
        paths:
          - path: /auth
            pathType: Prefix
            backend:
              service:
                name: authentication-service
                port:
                  number: {{ .Values.authenticationService.service.port }}
          - path: /course
            pathType: Prefix
            backend:
              service:
                name: coursemgmt-service
                port:
                  number: {{ .Values.coursemgmtService.service.port }}
          - path: /upload
            pathType: Prefix
            backend:
              service:
                name: upload-service
                port:
                  number: {{ .Values.uploadService.service.port }}
{{- end }}
