apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: {{ .Values.team }}
spec:
  selector:
    app: postgres
  ports:
    - port: {{ .Values.postgres.service.port }}
      targetPort: {{ .Values.postgres.service.port }}
      protocol: TCP
  type: {{ .Values.postgres.service.type }}