apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: {{ .Values.monitoring.namespace }}
data:
  prometheus.yml: |-
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: [ 'localhost:9090' ]

      - job_name: 'genai-service'
        static_configs:
          - targets: ['genai-service.{{ .Values.team }}.svc.cluster.local:8000']

      - job_name: 'authentication-service'
        static_configs:
          - targets: ['authentication-service.{{ .Values.team }}.svc.cluster.local:8080']
        metrics_path: '/actuator/prometheus'

      - job_name: 'coursemgmt-service'
        static_configs:
          - targets: ['coursemgmt-service.{{ .Values.team }}.svc.cluster.local:8080']
        metrics_path: '/actuator/prometheus'

      - job_name: 'upload-service'
        static_configs:
          - targets: ['upload-service.{{ .Values.team }}.svc.cluster.local:8080']
        metrics_path: '/actuator/prometheus'