apiVersion: v1
kind: Service
metadata:
  name: upload-service
  namespace: "{{ .Values.team }}"
spec:
  type: {{ .Values.uploadService.service.type | default "ClusterIP" }}
  selector:
    app: upload-service
  ports:
    - port: {{ .Values.uploadService.service.port }}
      targetPort: {{ .Values.uploadService.service.targetPort | default 8080 }}