apiVersion: v1
kind: Service
metadata:
  name: upload-service
  namespace: "{{ .Values.team }}"
spec:
  selector:
    app: upload-service-selector
  ports:
    - port: {{ .Values.uploadService.service.port }}
      targetPort: {{ .Values.uploadService.service.targetPort }}
      protocol: TCP
  type: {{ .Values.uploadService.service.type }}
