name: Client CI

on:
  push:
    branches: ["**"]

defaults:
  run:
    working-directory: ./client

jobs:
  lint-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "pnpm"
          cache-dependency-path: "**/pnpm-lock.yaml"

      - name: Install dependencies
        run: pnpm install

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: ./client/node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('./client/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      - name: Security audit
        run: pnpm audit

      - name: Lint
        run: pnpm lint

      - name: Build
        run: pnpm build

      - name: Cache build output
        uses: actions/cache@v4
        with:
          path: ./client/dist
          key: build-${{ github.sha }}

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: ./client/dist/
          retention-days: 1

  e2e-test:
    needs: lint-and-build
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Docker Compose
        uses: docker/setup-compose-action@v1

      - name: Set up and start services
        working-directory: .
        run: |
          # This service still needs its own .env file, so we create it
          mkdir -p ./genai
          echo "CHAIR_API_KEY=${CHAIR_API_KEY}" > ./genai/.env
          # : yes this should be empty
          echo "NEXT_PUBLIC_API_URL=" > ./client/.env.local
          echo "JWT_SECRET=08856eb694ef8c41d3ebe9a526597613e149c1762294d749e2f33f98281cf431" >> ./client/.env.local
          echo "JWT_SECRET=08856eb694ef8c41d3ebe9a526597613e149c1762294d749e2f33f98281cf431" > ./env

          # docker-compose will automatically pick up JWT_SECRET from the environment
          echo "Starting Docker services..."
          docker compose up -d

          echo "Waiting for services to be ready..."
          sleep 30

          docker compose ps -a
          echo "==== Docker Compose Logs ===="
          docker compose logs

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "pnpm"
          cache-dependency-path: "**/pnpm-lock.yaml"

      - name: Install dependencies
        run: pnpm install

      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps

      - name: Cache Playwright browsers
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: playwright-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            playwright-${{ runner.os }}-

      - name: Run Playwright tests against Docker services
        env:
          PLAYWRIGHT_BASE_URL: "http://localhost"
        run: |
          # Configure playwright to use the dockerized application URL
          pnpm exec playwright test

      - name: Print client logs on failure
        if: failure()
        run: |
          cd ..
          echo "==== Docker Compose Client Logs ===="
          docker compose logs client

      - name: Upload test report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: ./client/playwright-report/
          retention-days: 30

      - name: Stop Docker Compose services
        if: always()
        run: |
          cd ..
          docker-compose down -v
