name: Deploy to Kubernetes

on:
  workflow_dispatch:
  push:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config

      - name: Set up Helm
        uses: azure/setup-helm@v4

      - name: Set up kubectl
        uses: azure/setup-kubectl@v4

      - name: Helm dependencies (if needed)
        run: |
          helm dependency update ./helm/releaserangersapp

      - name: Deploy Helm chart
        run: |
          helm upgrade --install releaserangersapp ./helm/releaserangersapp \
            -n releaserangers --create-namespace \
            -f ./helm/releaserangersapp/values.yaml
      
      - name: Force rollout restart for all deployments
        run: |
          kubectl rollout restart deployment -n releaserangers

      - name: Show pods
        run: kubectl get pods -n releaserangers